server:
  servlet:
    context-path: /label

spring:
  datasource:
    url: jdbc:mysql://132.232.105.89:3306/silly_label?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: betaUser
    password: betaUser
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379


swagger.enable: true
logging:
  config: classpath:logback.xml
  path: /Users/yangrichard/Desktop/project/server/logs
